# 脚本配置
[run_config]
# 运行延迟间隔，值越小脚本处理速度越快，不建议小于1，默认4
run_delay = 4


# 自定义配置
[custom_config]
# 设置最近几天之内要处理的视频，默认2
days = 2
# 设置当浏览量大于多少要处理的视频(和days配置配合使用)，默认5500
max_video_count = 5500
# 设置当以上两个配置都触发后的视频是否公开或隐藏(1:所有人可见,3:仅自己可见)，默认值3
video_visible_type = 3
# 自动回复评论内容
auto_send_comment_text = "你好我是config toml test 评论回复"
# 自动回复私信文字内容
auto_send_private_msg = "你好我是私信的 config tmol test IMG1"
# 自动回复私信图片文件路径
auto_send_img_path = "D:/wx_video_api/QR.png"
